inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - "db/**/*.rb"
    - "vendor/**/*"

Naming/FileName:
  Exclude:
    - 'gems/decidim-galdakao_census/lib/decidim-galdakao_census.rb'